name = "stockvision"
compatibility_date = "2024-01-01"
main = "dist/index.js"

[build]
command = "npm run build"
cwd = "."
watch_paths = ["src/**/*.tsx", "src/**/*.ts"]

[env.production]
vars = { ENVIRONMENT = "production" }

[[routes]]
pattern = "*"